### ISSUE TITLE
Keep in sync with Prisma Markdown Plugin?

### ISSUE THREAD

**Issue by hongkongkiwi** [jiashengguo/zenstack-markdown#1]
Since there is a fantastic markdown plugin available already for Prisma, is it possible to update this to fork off of that and just add in any Zenstack specific extras? That would mean it's a simple effort to keep this updated without having to keep something completely new in sync.

**Comment by jiashengguo** [comment]
@hongkongkiwi,  thanks for the suggestion! I would love to make it part of the Prisma plugin, but I doubt the owner would agree since not all are ZenStack users. 

Moreover, the implementations are entirely different. Prisma's plugin uses Prisma's AST DMMF to accomplish its task, while this one uses ZenStack's AST, which also demonstrates how to develop a ZenStack plugin.   

Btw, I just updated it with the ability to leverage AI to generate a more meaningful doc.

**Comment by hongkongkiwi** [comment]
That makes perfect sense. Now I understand Zenstack architecture a little bit better.

Nice work on the AI integration! :D
